export const DEMO = {
  projects: [
    {
      gizmoId: "g-wp",
      title: "WordPress Plugin Lab",
      href: "#",
      conversations: [
        { id: "c-wp-01", title: "Gutenberg block structure: block.json and edit/save", gizmoId: "g-wp" },
        { id: "c-wp-02", title: "Theme.json tokens: using WP preset colors properly", gizmoId: "g-wp" },
        { id: "c-wp-03", title: "Shortcodes vs blocks: when to use what", gizmoId: "g-wp" },
        { id: "c-wp-04", title: "WP REST API auth: nonce + cookies vs app passwords", gizmoId: "g-wp" },
        { id: "c-wp-05", title: "Plugin build pipeline: webpack vs Vite for blocks", gizmoId: "g-wp" },
        { id: "c-wp-06", title: "Internationalization: __(), _x(), and build steps", gizmoId: "g-wp" },
        { id: "c-wp-07", title: "Security checklist: sanitize, escape, capability checks", gizmoId: "g-wp" },
        { id: "c-wp-08", title: "FSE templates: managing patterns and template parts", gizmoId: "g-wp" },
        { id: "c-wp-09", title: "WP-CLI automation: exports, imports, and resets", gizmoId: "g-wp" },
        { id: "c-wp-10", title: "Performance: object cache, transients, and query reduction", gizmoId: "g-wp" },
      ],
    },

    {
      gizmoId: "g-gh",
      title: "GitHub Workflow & Releases",
      href: "#",
      conversations: [
        { id: "c-gh-01", title: "Release assets: tagging strategy and upload via gh cli", gizmoId: "g-gh" },
        { id: "c-gh-02", title: "Changelog discipline: keep a version.md readable", gizmoId: "g-gh" },
        { id: "c-gh-03", title: "Repo hygiene: .gitignore, large files, and build artifacts", gizmoId: "g-gh" },
        { id: "c-gh-04", title: "Git add: '.' vs '-A' and deletion behavior", gizmoId: "g-gh" },
        { id: "c-gh-05", title: "PR workflow: branch naming and small reviewable commits", gizmoId: "g-gh" },
        { id: "c-gh-06", title: "CI basics: lint, typecheck, build, and release gates", gizmoId: "g-gh" },
      ],
    },

    {
      gizmoId: "g-chrome-ext",
      title: "Chrome Extension Engineering",
      href: "#",
      conversations: [
        { id: "c-chx-01", title: "Manifest V3 overview: service worker + permissions", gizmoId: "g-chrome-ext" },
        { id: "c-chx-02", title: "Messaging patterns: panel ↔ background ↔ content", gizmoId: "g-chrome-ext" },
        { id: "c-chx-03", title: "Storage: chrome.storage.local vs session", gizmoId: "g-chrome-ext" },
        { id: "c-chx-04", title: "Rate limiting: throttling delete operations safely", gizmoId: "g-chrome-ext" },
        { id: "c-chx-05", title: "UI: side panel architecture and tab routing", gizmoId: "g-chrome-ext" },
        { id: "c-chx-06", title: "Testing: creating a demo mode with mocked seams", gizmoId: "g-chrome-ext" },
        { id: "c-chx-07", title: "Error handling: retry policies and progress events", gizmoId: "g-chrome-ext" },
        { id: "c-chx-08", title: "Packaging: dist layout and release zip scripts", gizmoId: "g-chrome-ext" },
      ],
    },

    {
      gizmoId: "g-firefox-ext",
      title: "Firefox Extension Port (WebExtensions)",
      href: "#",
      conversations: [
        { id: "c-ffx-01", title: "Chrome vs Firefox APIs: browser.* polyfills and gaps", gizmoId: "g-firefox-ext" },
        { id: "c-ffx-02", title: "MV3 support status: what to avoid for portability", gizmoId: "g-firefox-ext" },
        { id: "c-ffx-03", title: "Side panel alternatives: UI constraints in Firefox", gizmoId: "g-firefox-ext" },
        { id: "c-ffx-04", title: "Packaging & signing: AMO upload checklist", gizmoId: "g-firefox-ext" },
      ],
    },

    {
      gizmoId: "g-vite",
      title: "Vite Build System",
      href: "#",
      conversations: [
        { id: "c-vite-01", title: "Vite plugins: resolveId hooks and swapping seams", gizmoId: "g-vite" },
        { id: "c-vite-02", title: "Static asset emission: generateBundle and fileName paths", gizmoId: "g-vite" },
        { id: "c-vite-03", title: "Dev vs build parity: ensuring preview matches prod", gizmoId: "g-vite" },
        { id: "c-vite-04", title: "Aliasing strategies: regex alias vs plugin-based swapping", gizmoId: "g-vite" },
        { id: "c-vite-05", title: "TypeScript imports: allowImportingTsExtensions pitfalls", gizmoId: "g-vite" },
      ],
    },

    {
      gizmoId: "g-node",
      title: "Node.js Backend Patterns",
      href: "#",
      conversations: [
        { id: "c-node-01", title: "HTTP server basics: Express vs Fastify tradeoffs", gizmoId: "g-node" },
        { id: "c-node-02", title: "Logging: structured logs and request correlation IDs", gizmoId: "g-node" },
        { id: "c-node-03", title: "Auth: session cookies vs JWT in practice", gizmoId: "g-node" },
        { id: "c-node-04", title: "Error boundaries: central error middleware strategy", gizmoId: "g-node" },
        { id: "c-node-05", title: "Rate limiting: burst control and backoff policies", gizmoId: "g-node" },
        { id: "c-node-06", title: "Deployment: process managers and health endpoints", gizmoId: "g-node" },
        { id: "c-node-07", title: "Security headers: CSP, HSTS, and X-Frame-Options", gizmoId: "g-node" },
        { id: "c-node-08", title: "Postgres patterns: migrations, pool sizing, retries", gizmoId: "g-node" },
        { id: "c-node-09", title: "Queues: background jobs and idempotency keys", gizmoId: "g-node" },
        { id: "c-node-10", title: "Monorepo setup: shared types and build pipelines", gizmoId: "g-node" },
        { id: "c-node-11", title: "Observability: metrics, tracing, dashboards", gizmoId: "g-node" },
      ],
    },

    {
      gizmoId: "g-ts",
      title: "TypeScript Deep Dive",
      href: "#",
      conversations: [
        { id: "c-ts-01", title: "Discriminated unions for message buses", gizmoId: "g-ts" },
        { id: "c-ts-02", title: "Narrowing: type guards and exhaustive checks", gizmoId: "g-ts" },
        { id: "c-ts-03", title: "Strict mode: fixing implicit any and unknown", gizmoId: "g-ts" },
        { id: "c-ts-04", title: "API typing: request/response alignment and reuse", gizmoId: "g-ts" },
        { id: "c-ts-05", title: "Build targets: ESM, CJS, and browser bundles", gizmoId: "g-ts" },
        { id: "c-ts-06", title: "Module resolution: paths, aliases, and tooling", gizmoId: "g-ts" },
        { id: "c-ts-07", title: "Runtime validation: zod vs manual checks", gizmoId: "g-ts" },
        { id: "c-ts-08", title: "Error types: designing safe error objects", gizmoId: "g-ts" },
      ],
    },

    {
      gizmoId: "g-ai",
      title: "AI Engineering Notes",
      href: "#",
      conversations: [
        { id: "c-ai-01", title: "Prompt design: constraints, examples, and failure modes", gizmoId: "g-ai" },
        { id: "c-ai-02", title: "RAG pipeline: chunking and retrieval tuning", gizmoId: "g-ai" },
        { id: "c-ai-03", title: "Evaluation: golden sets and regression tests", gizmoId: "g-ai" },
        { id: "c-ai-04", title: "Safety: what to log vs what not to log", gizmoId: "g-ai" },
        { id: "c-ai-05", title: "Latency: caching, streaming, and batching strategies", gizmoId: "g-ai" },
        { id: "c-ai-06", title: "Cost control: token budgets and request shaping", gizmoId: "g-ai" },
        { id: "c-ai-07", title: "Agent orchestration: tools, retries, and guardrails", gizmoId: "g-ai" },
        { id: "c-ai-08", title: "Model selection: quality vs speed tradeoffs", gizmoId: "g-ai" },
        { id: "c-ai-09", title: "Data privacy: redaction strategies and minimization", gizmoId: "g-ai" },
        { id: "c-ai-10", title: "Vector DB options: what matters in production", gizmoId: "g-ai" },
        { id: "c-ai-11", title: "Embedding drift: how to re-index safely", gizmoId: "g-ai" },
        { id: "c-ai-12", title: "Fine-tuning vs prompting: decision checklist", gizmoId: "g-ai" },
        { id: "c-ai-13", title: "Multi-language: tokenization surprises and UX", gizmoId: "g-ai" },
        { id: "c-ai-14", title: "Human-in-the-loop: review workflows that scale", gizmoId: "g-ai" },
        { id: "c-ai-15", title: "Incident playbook: model outages and fallback plans", gizmoId: "g-ai" },
      ],
    },

    {
      gizmoId: "g-algo",
      title: "Algorithms & Data Structures",
      href: "#",
      conversations: [
        { id: "c-algo-01", title: "Big-O in real life: when it actually matters", gizmoId: "g-algo" },
        { id: "c-algo-02", title: "Graphs: BFS/DFS patterns and common mistakes", gizmoId: "g-algo" },
        { id: "c-algo-03", title: "Sorting: stable vs unstable and why you care", gizmoId: "g-algo" },
        { id: "c-algo-04", title: "Hashing: collisions, load factors, and performance", gizmoId: "g-algo" },
        { id: "c-algo-05", title: "Dynamic programming: memoization strategy guide", gizmoId: "g-algo" },
        { id: "c-algo-06", title: "Heaps: priority queues for scheduling tasks", gizmoId: "g-algo" },
        { id: "c-algo-07", title: "Bit tricks: fast masks and feature flags", gizmoId: "g-algo" },
        { id: "c-algo-08", title: "Strings: prefix functions, tries, and search", gizmoId: "g-algo" },
        { id: "c-algo-09", title: "Caching: LRU designs and edge cases", gizmoId: "g-algo" },
      ],
    },

    {
      gizmoId: "g-sec",
      title: "Security & Hardening",
      href: "#",
      conversations: [
        { id: "c-sec-01", title: "CSP practical guide: reducing XSS risk", gizmoId: "g-sec" },
        { id: "c-sec-02", title: "CSRF: why it still bites modern apps", gizmoId: "g-sec" },
        { id: "c-sec-03", title: "Secrets management: env files vs vault", gizmoId: "g-sec" },
        { id: "c-sec-04", title: "Supply chain: npm audit realities and mitigation", gizmoId: "g-sec" },
        { id: "c-sec-05", title: "AuthZ: roles, scopes, and permission boundaries", gizmoId: "g-sec" },
        { id: "c-sec-06", title: "OWASP Top 10: the parts that actually show up", gizmoId: "g-sec" },
        { id: "c-sec-07", title: "Rate limiting & abuse: bots and scraping controls", gizmoId: "g-sec" },
        { id: "c-sec-08", title: "Server headers: hardening for modern browsers", gizmoId: "g-sec" },
        { id: "c-sec-09", title: "Cookie flags: SameSite, Secure, HttpOnly usage", gizmoId: "g-sec" },
        { id: "c-sec-10", title: "Dependency pinning: lockfiles and reproducibility", gizmoId: "g-sec" },
        { id: "c-sec-11", title: "TLS basics: certificates, renewals, and traps", gizmoId: "g-sec" },
        { id: "c-sec-12", title: "App isolation: containers and least privilege", gizmoId: "g-sec" },
        { id: "c-sec-13", title: "Logging sensitive data: redaction rules", gizmoId: "g-sec" },
      ],
    },

    {
      gizmoId: "g-license",
      title: "Licenses & Compliance",
      href: "#",
      conversations: [
        { id: "c-lic-01", title: "MIT vs Apache-2.0: practical differences", gizmoId: "g-license" },
        { id: "c-lic-02", title: "GPL concerns: linking, distribution, and obligations", gizmoId: "g-license" },
        { id: "c-lic-03", title: "Third-party notices: what to ship with releases", gizmoId: "g-license" },
      ],
    },

    {
      gizmoId: "g-cpp",
      title: "C++ Foundations",
      href: "#",
      conversations: [
        { id: "c-cpp-01", title: "Modern C++: RAII, smart pointers, and ownership", gizmoId: "g-cpp" },
        { id: "c-cpp-02", title: "Build systems: CMake patterns that don’t hurt", gizmoId: "g-cpp" },
        { id: "c-cpp-03", title: "Undefined behavior: why it is worse than bugs", gizmoId: "g-cpp" },
        { id: "c-cpp-04", title: "Move semantics: when it actually helps", gizmoId: "g-cpp" },
        { id: "c-cpp-05", title: "Templates: compile-time errors and diagnostics", gizmoId: "g-cpp" },
      ],
    },

    {
      gizmoId: "g-python",
      title: "Python Tooling",
      href: "#",
      conversations: [
        { id: "c-py-01", title: "Virtualenv vs Poetry vs uv: picking one", gizmoId: "g-python" },
        { id: "c-py-02", title: "Type hints: mypy/pyright strategy", gizmoId: "g-python" },
        { id: "c-py-03", title: "FastAPI patterns: dependencies and testing", gizmoId: "g-python" },
        { id: "c-py-04", title: "Packaging: wheels, sdists, and versioning", gizmoId: "g-python" },
        { id: "c-py-05", title: "Scripting: CLI ergonomics and config layout", gizmoId: "g-python" },
        { id: "c-py-06", title: "Data processing: pandas performance basics", gizmoId: "g-python" },
        { id: "c-py-07", title: "Async: when to use asyncio and when not", gizmoId: "g-python" },
      ],
    },

    {
      gizmoId: "g-docker",
      title: "Docker & Compose",
      href: "#",
      conversations: [
        { id: "c-dk-01", title: "Compose profiles: clean dev vs prod separation", gizmoId: "g-docker" },
        { id: "c-dk-02", title: "Healthchecks: making dependencies reliable", gizmoId: "g-docker" },
        { id: "c-dk-03", title: "Volumes: avoiding permission hell with UID/GID", gizmoId: "g-docker" },
        { id: "c-dk-04", title: "Build stages: small images and fast rebuilds", gizmoId: "g-docker" },
        { id: "c-dk-05", title: "Reverse proxy patterns: Apache vs Nginx", gizmoId: "g-docker" },
        { id: "c-dk-06", title: "Static hosting container: serving dist/ safely", gizmoId: "g-docker" },
        { id: "c-dk-07", title: "Secrets: env files vs Docker secrets", gizmoId: "g-docker" },
        { id: "c-dk-08", title: "Network: internal URLs and cross-service calls", gizmoId: "g-docker" },
      ],
    },

    {
      gizmoId: "g-next",
      title: "Next.js Notes",
      href: "#",
      conversations: [
        { id: "c-next-01", title: "App Router: layouts, pages, and route handlers", gizmoId: "g-next" },
        { id: "c-next-02", title: "Deployment: build output and runtime configs", gizmoId: "g-next" },
        { id: "c-next-03", title: "Static assets: serving under a subpath cleanly", gizmoId: "g-next" },
        { id: "c-next-04", title: "Auth flow: proxy headers and cookie security", gizmoId: "g-next" },
        { id: "c-next-05", title: "Performance: bundle analysis and caching", gizmoId: "g-next" },
      ],
    },

    {
      gizmoId: "g-rest",
      title: "REST API Design",
      href: "#",
      conversations: [
        { id: "c-rest-01", title: "Pagination: cursor vs offset", gizmoId: "g-rest" },
        { id: "c-rest-02", title: "Error formats: consistent error contracts", gizmoId: "g-rest" },
      ],
    },

    {
      gizmoId: "g-uiux",
      title: "UI/UX for Developer Tools",
      href: "#",
      conversations: [
        { id: "c-ui-01", title: "Progress UI: what users need to trust it", gizmoId: "g-uiux" },
        { id: "c-ui-02", title: "Confirmation dialogs: reducing destructive mistakes", gizmoId: "g-uiux" },
        { id: "c-ui-03", title: "Information density: logs that stay readable", gizmoId: "g-uiux" },
        { id: "c-ui-04", title: "Keyboard navigation: focus order and ARIA basics", gizmoId: "g-uiux" },
        { id: "c-ui-05", title: "UX copy: writing status messages that aren’t lies", gizmoId: "g-uiux" },
        { id: "c-ui-06", title: "Empty states: making the UI feel alive", gizmoId: "g-uiux" },
        { id: "c-ui-07", title: "Filter/search: fast client-side techniques", gizmoId: "g-uiux" },
        { id: "c-ui-08", title: "Design tokens: theme-aware colors and spacing", gizmoId: "g-uiux" },
        { id: "c-ui-09", title: "Accessibility: contrast and reduced motion", gizmoId: "g-uiux" },
        { id: "c-ui-10", title: "Responsive layout: two-column split strategies", gizmoId: "g-uiux" },
        { id: "c-ui-11", title: "Error feedback: inline vs toast vs log-only", gizmoId: "g-uiux" },
        { id: "c-ui-12", title: "Consistency: reusable components in the panel", gizmoId: "g-uiux" },
      ],
    },

    {
      gizmoId: "g-testing",
      title: "Testing & QA",
      href: "#",
      conversations: [
        { id: "c-tst-01", title: "Smoke tests: verifying build artifacts exist", gizmoId: "g-testing" },
        { id: "c-tst-02", title: "Type-check gates: catching message schema drift", gizmoId: "g-testing" },
        { id: "c-tst-03", title: "Mocking seams: runtime + storage wrappers", gizmoId: "g-testing" },
        { id: "c-tst-04", title: "Regression tests: keep demo data stable for screenshots", gizmoId: "g-testing" },
        { id: "c-tst-05", title: "E2E: controlling flakiness with deterministic fixtures", gizmoId: "g-testing" },
        { id: "c-tst-06", title: "Error injection: simulate failures and retries", gizmoId: "g-testing" },
        { id: "c-tst-07", title: "Performance: measuring UI responsiveness", gizmoId: "g-testing" },
      ],
    },

    {
      gizmoId: "g-arch",
      title: "Architecture & Refactors",
      href: "#",
      conversations: [
        { id: "c-arch-01", title: "Separating platform seams: runtime, storage, fetch", gizmoId: "g-arch" },
        { id: "c-arch-02", title: "Cache strategy: snapshots and subscriptions", gizmoId: "g-arch" },
        { id: "c-arch-03", title: "Events vs responses: progress events contract", gizmoId: "g-arch" },
        { id: "c-arch-04", title: "Logging tiers: audit log vs debug trace", gizmoId: "g-arch" },
        { id: "c-arch-05", title: "Config handling: dev config vs API config", gizmoId: "g-arch" },
        { id: "c-arch-06", title: "Keeping code clean: no backward compatibility hacks", gizmoId: "g-arch" },
        { id: "c-arch-07", title: "Message typing: union composition in shared/messages", gizmoId: "g-arch" },
        { id: "c-arch-08", title: "Organize tab: confirm UI layout improvements", gizmoId: "g-arch" },
        { id: "c-arch-09", title: "Scope system: YMD filtering and out-of-scope guard", gizmoId: "g-arch" },
        { id: "c-arch-10", title: "Release tooling: zip builds and GitHub automation", gizmoId: "g-arch" },
        { id: "c-arch-11", title: "Demo packaging: dist independence and embedding", gizmoId: "g-arch" },
      ],
    },

    {
      gizmoId: "g-misc",
      title: "Misc Notes & Scratchpad",
      href: "#",
      conversations: [
        { id: "c-misc-01", title: "Naming: choosing clear message constants", gizmoId: "g-misc" },
        { id: "c-misc-02", title: "UI polish: microcopy and empty state wording", gizmoId: "g-misc" },
      ],
    },
  ],

  singles: [
    { id: "c-s-01", title: "Quickstart: build and load unpacked extension", gizmoId: "" },
    { id: "c-s-02", title: "Debugging: why a tab click does nothing", gizmoId: "" },
    { id: "c-s-03", title: "Vite: dev vs preview and why it matters", gizmoId: "" },
    { id: "c-s-04", title: "TypeScript error: union event types mismatch", gizmoId: "" },
    { id: "c-s-05", title: "Chrome storage: local vs sync differences", gizmoId: "" },
    { id: "c-s-06", title: "Design: two-column layout for safer confirmations", gizmoId: "" },
    { id: "c-s-07", title: "Security: CSP and embedding via iframe", gizmoId: "" },
    { id: "c-s-08", title: "Git: stash vs commit for interrupted scripts", gizmoId: "" },
    { id: "c-s-09", title: "Release automation: tag + upload assets", gizmoId: "" },
    { id: "c-s-10", title: "Node audit: handling moderate vulnerabilities", gizmoId: "" },
    { id: "c-s-11", title: "Next.js proxy: Apache headers and websocket upgrade", gizmoId: "" },
    { id: "c-s-12", title: "Mocking: seam swap for runtime and storage", gizmoId: "" },
    { id: "c-s-13", title: "API design: progress events contract", gizmoId: "" },
    { id: "c-s-14", title: "UI: logs tab export and trimming strategy", gizmoId: "" },
    { id: "c-s-15", title: "Organize: moving chats to projects workflow", gizmoId: "" },
    { id: "c-s-16", title: "Performance: caching and update throttling", gizmoId: "" },
    { id: "c-s-17", title: "License: choosing MIT vs Apache for a tool", gizmoId: "" },
    { id: "c-s-18", title: "CSS: why panel looks ugly in demo build", gizmoId: "" },
    { id: "c-s-19", title: "Troubleshooting: missing DOM id errors in panel", gizmoId: "" },
  ],
};
 